-- Создание таблицы двигателей
CREATE TABLE engines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    volume DOUBLE,
    power INT
);

COMMENT ON TABLE engines IS 'Таблица двигателей';
COMMENT ON COLUMN engines.name IS 'Название двигателя';
COMMENT ON COLUMN engines.volume IS 'Объем двигателя (л)';
COMMENT ON COLUMN engines.power IS 'Мощность двигателя (л.с.)';

-- Создание таблицы автомобилей
CREATE TABLE cars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    model VARCHAR(50),
    manufacture_year INT,
    engine_id INT NOT NULL UNIQUE REFERENCES engines(id)
);

COMMENT ON TABLE cars IS 'Таблица автомобилей';
COMMENT ON COLUMN cars.name IS 'Название/марка автомобиля';
COMMENT ON COLUMN cars.model IS 'Модель автомобиля';
COMMENT ON COLUMN cars.manufacture_year IS 'Год выпуска';
COMMENT ON COLUMN cars.engine_id IS 'Ссылка на двигатель (One-to-One)';