-- Создание таблицы истории цен
CREATE TABLE price_history (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   before BIGINT NOT NULL,
   after BIGINT,
   created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   post_id INTEGER REFERENCES auto_post(id)
);

COMMENT ON TABLE price_history IS 'История изменения цен в объявлениях';
COMMENT ON COLUMN price_history.before IS 'Цена до изменения';
COMMENT ON COLUMN price_history.after IS 'Цена после изменения';
COMMENT ON COLUMN price_history.created IS 'Дата изменения цены';
COMMENT ON COLUMN price_history.post_id IS 'Ссылка на объявление';