-- Создание таблицы владельцев
CREATE TABLE owners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    user_id INT REFERENCES auto_user(id)
);

COMMENT ON TABLE owners IS 'Таблица владельцев автомобилей';
COMMENT ON COLUMN owners.name IS 'Имя владельца';
COMMENT ON COLUMN owners.user_id IS 'Ссылка на пользователя системы';

-- Создание таблицы для связи many-to-many (владельцы-автомобили)
CREATE TABLE history_owner (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INT NOT NULL REFERENCES cars(id),
    owner_id INT NOT NULL REFERENCES owners(id),
    start_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_at TIMESTAMP
);

COMMENT ON TABLE history_owner IS 'История владения автомобилями';
COMMENT ON COLUMN history_owner.car_id IS 'Ссылка на автомобиль';
COMMENT ON COLUMN history_owner.owner_id IS 'Ссылка на владельца';
COMMENT ON COLUMN history_owner.start_at IS 'Дата начала владения';
COMMENT ON COLUMN history_owner.end_at IS 'Дата окончания владения';