-- ============================================
-- DDL: Создание структуры базы данных cars_db
-- Порядок: от независимых таблиц к зависимым
-- ============================================

-- 1. Таблица пользователей (самая независимая)
CREATE TABLE auto_user (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL
);

COMMENT ON TABLE auto_user IS 'Таблица пользователей автосайта';
COMMENT ON COLUMN auto_user.login IS 'Уникальный логин пользователя';
COMMENT ON COLUMN auto_user.password IS 'Пароль пользователя';

-- 2. Таблица двигателей (не зависит от других таблиц)
CREATE TABLE engines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    volume DOUBLE,
    power INT
);

COMMENT ON TABLE engines IS 'Таблица двигателей';
COMMENT ON COLUMN engines.name IS 'Название двигателя';
COMMENT ON COLUMN engines.volume IS 'Объем двигателя (л)';
COMMENT ON COLUMN engines.power IS 'Мощность двигателя (л.с.)';

-- 3. Таблица автомобилей (зависит от engines)
CREATE TABLE cars (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    model VARCHAR(50),
    manufacture_year INT,
    engine_id INT NOT NULL REFERENCES engines(id)
);

COMMENT ON TABLE cars IS 'Таблица автомобилей';
COMMENT ON COLUMN cars.name IS 'Название/марка автомобиля';
COMMENT ON COLUMN cars.model IS 'Модель автомобиля';
COMMENT ON COLUMN cars.manufacture_year IS 'Год выпуска';
COMMENT ON COLUMN cars.engine_id IS 'Ссылка на двигатель (One-to-One)';

-- 4. Таблица объявлений (зависит от auto_user и cars)
CREATE TABLE auto_post (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description TEXT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    currentPrice BIGINT,
    car_id INTEGER REFERENCES cars(id),
    auto_user_id INTEGER NOT NULL REFERENCES auto_user(id)
);

COMMENT ON TABLE auto_post IS 'Таблица объявлений о продаже автомобилей';
COMMENT ON COLUMN auto_post.description IS 'Описание автомобиля';
COMMENT ON COLUMN auto_post.created IS 'Дата создания объявления';
COMMENT ON COLUMN auto_post.currentPrice IS 'Текущая цена автомобиля';
COMMENT ON COLUMN auto_post.car_id IS 'Ссылка на автомобиль';
COMMENT ON COLUMN auto_post.auto_user_id IS 'Ссылка на пользователя-автора';

-- 5. Таблица истории цен (зависит от auto_post)
CREATE TABLE price_history (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   before BIGINT NOT NULL,
   after BIGINT,
   created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   post_id INTEGER REFERENCES auto_post(id)
);

COMMENT ON TABLE price_history IS 'История изменения цен в объявлениях';
COMMENT ON COLUMN price_history.before IS 'Цена до изменения';
COMMENT ON COLUMN price_history.after IS 'Цена после изменения';
COMMENT ON COLUMN price_history.created IS 'Дата изменения цены';
COMMENT ON COLUMN price_history.post_id IS 'Ссылка на объявление';

-- 6. Таблица подписок/участия (зависит от auto_user и auto_post)
CREATE TABLE participates (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES auto_user(id),
    post_id INT NOT NULL REFERENCES auto_post(id),
    created TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, post_id)
);

-- 7. Таблица владельцев (зависит от auto_user)
CREATE TABLE owners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    user_id INT REFERENCES auto_user(id)
);

COMMENT ON TABLE owners IS 'Таблица владельцев автомобилей';
COMMENT ON COLUMN owners.name IS 'Имя владельца';
COMMENT ON COLUMN owners.user_id IS 'Ссылка на пользователя системы';

-- 8. Таблица истории владения (зависит от cars и owners)
CREATE TABLE history_owner (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id INT NOT NULL REFERENCES cars(id),
    owner_id INT NOT NULL REFERENCES owners(id),
    start_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    end_at TIMESTAMP
);

COMMENT ON TABLE history_owner IS 'История владения автомобилями';
COMMENT ON COLUMN history_owner.car_id IS 'Ссылка на автомобиль';
COMMENT ON COLUMN history_owner.owner_id IS 'Ссылка на владельца';
COMMENT ON COLUMN history_owner.start_at IS 'Дата начала владения';
COMMENT ON COLUMN history_owner.end_at IS 'Дата окончания владения';

-- 9. Таблица фотографий (зависит от auto_post)
CREATE TABLE post_photos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id INTEGER NOT NULL REFERENCES auto_post(id) ON DELETE CASCADE,
    photo_url VARCHAR(500) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE post_photos IS 'Фотографии объявлений о продаже автомобилей';
COMMENT ON COLUMN post_photos.post_id IS 'Ссылка на объявление';
COMMENT ON COLUMN post_photos.photo_url IS 'URL фотографии';
COMMENT ON COLUMN post_photos.created IS 'Дата добавления фото';

-- Индексы для оптимизации
CREATE INDEX idx_post_photos_post_id ON post_photos(post_id);